spring.application.name=maliexplorer-backend
server.port=8080

# Configuration Base de données avec variables et création automatique si absente
spring.datasource.url=jdbc:mysql://\({DB_HOST:localhost}:\){DB_PORT:3306}/${DB_NAME:maliexplorer_db}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Africa/Bamako&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Documentation OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha